export const ConditionDashboardTitles = [
  "Helps with ",
  "Relief for ",
];

export const SymptomDashboardTitles = [
  "Helps with ",
  "Relief for ",
];

export const EffectsDashboardTitles = [
  "If you want to feel ",
  "Strains to make you ",
];

export const StrainTypeDashboardTitles = [
  "If you want to try a ",
  "For people looking for a ",
];

export const StrainTypeDashboardIndicaTitles = [
  "If you want to try an ",
  "For people looking for an ",
];

/**
 * Returns a randomized title text for a given group type and name.
 * The title is generated by selecting a random prefix from a predefined list
 * (based on the group type) and concatenating it with the provided name.
 *
 * @function getRandomTitle
 * @param {string} type - The group type (e.g., "conditions", "symptoms", "effects", "strain").
 * @param {string} name - The name or value associated with the group (e.g., "Hybrid", "Anxiety").
 * @return {string} A formatted title string combining a random prefix and the name.
 *
 * @example
 * // Example usage:
 * getRandomTitle("strain", "Hybrid");
 * // → "If you want to try a Hybrid"
 */
export function getRandomTitle(type: string, name: string): string {
  let titles: string[] = [];

  switch (type) {
  case "conditions":
    titles = ConditionDashboardTitles;
    break;
  case "symptoms":
    titles = SymptomDashboardTitles;
    break;
  case "effects":
    titles = EffectsDashboardTitles;
    break;
  case "strain":
    // Indica uses special “an” wording
    titles = name.toLowerCase().startsWith("i") ?
      StrainTypeDashboardIndicaTitles :
      StrainTypeDashboardTitles;
    break;
  default:
    titles = ["Related to "];
  }

  const prefix = titles[Math.floor(Math.random() * titles.length)];
  return `${prefix}${name}`;
}
